### ISSUE TITLE
Image Not appearing

### ISSUE THREAD

**Issue by JhonTolentino** [JhonTolentino/portfolio#2]
@thomasjbradley problems with image not appearing from pattern cards. I am using the "card" pattern as the main test driver for getting pictures to appear. I feel like it has something to do with my config.yml in the card pattern folder. 
<img width="419" alt="Screen Shot 2019-12-10 at 11 20 28 AM" src="https://user-images.githubusercontent.com/22149566/70557013-0006ca00-1b50-11ea-8b4e-943da07452fc.png">
<img width="481" alt="Screen Shot 2019-12-10 at 11 09 02 AM" src="https://user-images.githubusercontent.com/22149566/70557019-039a5100-1b50-11ea-8038-69358c19e74d.png">
<img width="277" alt="Screen Shot 2019-12-10 at 10 50 48 AM" src="https://user-images.githubusercontent.com/22149566/70557028-072dd800-1b50-11ea-8f5e-e1b030d81600.png">

**Comment by thomasjbradley** [comment]
What page are you testing this on?

**Comment by JhonTolentino** [comment]
Don't worry Thomas I was tinkering with it last night, I figured out how to do it!


Jhon Tolentino

040842515


________________________________
